# CAMERA SOURCES
WEBCAM_INDEX = 0
ESP32_CAM_IP = "192.168.1.16"
ESP32_CAM_STREAM_URL = f"http://{ESP32_CAM_IP}/stream"
ESP32_CAM_STATUS_URL = f"http://{ESP32_CAM_IP}/status"

# DETECTION
PERSON_DETECTOR_MODEL = "yolov8n.pt"
PERSON_CONFIDENCE = 0.75
MIN_DETECTIONS = 5
USE_FACE_RECOGNITION = True
KNOWN_FACES_DIR = "known_faces"
FACE_ENCODINGS_CACHE = "face_encodings.pkl"
FACE_DISTANCE_THRESHOLD = 0.6
FACE_RECOGNITION_MIN_DETECTIONS = 3
YOLO_FACE_RECOGNITION_MODEL = r".\runs\face_detection\my_face_model5\weights\best.pt"

# PROCESSING
FRAME_SKIP = 3
IMAGE_SIZE = 640

# TELEGRAM
TELEGRAM_ENABLED = True
TELEGRAM_BOT_TOKEN = "8273347206:AAFpo42FcSeZD-aX6esX3vkKloYnbmLhXQ8"
TELEGRAM_CHAT_ID = "6210129406"
TELEGRAM_ALERT_COOLDOWN = 300

# STORAGE
IMAGES_DIR = "security_images"
SAVE_IMAGES = True
IMAGE_ARCHIVE_HOURS = 6
IMAGE_CLEANUP_INTERVAL_MINUTES = 30
LOGS_FILE = "security_log.json"
LOG_LEVEL = "INFO"

# SERVER
HOST = "0.0.0.0"
PORT = 8000
CORS_ORIGINS = ["*"]